name: Zip and Overwrite archives in the repository

on:
  workflow_dispatch:
  push:
      branches:
          - main

jobs:
  zip:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout with write access
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Configure Git
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

      - name: Zip directories
        run: |
          ./make_zips.sh

      - name: Commit updated zip files
        run: |
          git add *.zip
          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "Update zip files from GitHub Actions"
            git push
          fi
